/*
 * @Author: Jin X
 * @Date: 2020-07-09 23:06:27
 * @LastEditTime: 2020-07-09 23:08:42
 */ 
const ACTIONS = {
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    CHANGE_TODO: "CHANGE_TODO",
    TOGGLE_TODO: "TOGGLE_TODO",
    TOGGLE_ALL: "TOGGLE_ALL",
    REMOVE_COMPLETED: "REMOVE_COMPLETED",
};

module.exports = ACTIONS;