/*
 * @Author: Jin X
 * @Date: 2020-07-09 23:06:27
 * @LastEditTime: 2020-07-11 13:50:15
 */ 
const ACTIONS = {
    GET_ALL: "GET_ALL",
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    RENAME_TODO: "RENAME_TODO",
    TOGGLE_TODO: "TOGGLE_TODO",
    TOGGLE_ALL: "TOGGLE_ALL",
    REMOVE_COMPLETED: "REMOVE_COMPLETED",
};

module.exports = ACTIONS;